### ISSUE TITLE
make grader installable with pip

### ISSUE THREAD

**Issue by otizonaizit** [ASPP/grader#8]
This is long overdue. It shouldn't be too much of a problem, but there are some caveats:

  - we need to make the script `grader.py` available as `grader` in the user PATH (entry_point, scripts in setuptools?). I didn't check the last best practices in this regard, but it would be worth to do it before using a method which is already obsolete
  - we need to make the plugins (currently only `create_groups`) work: right now we can run them within the grader CLI using `grader> loadpy PLUGIN_PATH`. After installing with `pip` we will not know exactly where stuff got installed, so we need to make the plugins loadable just by name, i.e. `loadpy` should either execute a script at the path specified, or look for the name in the list of available plugins…

**Comment by pberkes** [comment]
Setup tools supports plugins, although I personally haven't used it

**Comment by otizonaizit** [comment]
Hm. I'm not sure our concept of *plugin* matches setuptools's one ;)  A plugin in grader is just a snippet of Python code that we want to be able to execute within the applications namespace, just a quick and dirty way of adding new functionality to grader without having to understand grader and/or modify it. When our refactoring is done plugins are probably going to be useless :)))
